// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UPgm60xZogGRsCJDO51sJc2zMl78p54',
    appId: '1:660419145983:web:227e297e28749fd44d9cca',
    messagingSenderId: '660419145983',
    projectId: 'summitapp-3634e',
    authDomain: 'summitapp-3634e.firebaseapp.com',
    storageBucket: 'summitapp-3634e.firebasestorage.app',
    measurementId: 'G-JQT5NJ063J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUts-9OO5Q0LbLsNpwnQkx7TYLxmyCAws',
    appId: '1:660419145983:android:5df06a45ca5648834d9cca',
    messagingSenderId: '660419145983',
    projectId: 'summitapp-3634e',
    storageBucket: 'summitapp-3634e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1q5bXkNTkAaumtW5CH_4bWP_kQ0iPhwM',
    appId: '1:660419145983:ios:55fe7fada95bc0cd4d9cca',
    messagingSenderId: '660419145983',
    projectId: 'summitapp-3634e',
    storageBucket: 'summitapp-3634e.firebasestorage.app',
    iosBundleId: 'com.carisca.summit2025',
  );
}
